version: '3'

tasks:
  init_artifact:
    dir: infra/artifact_repository
    cmds:
      - terraform init
  
  init_webshop:
    dir: infra/webshop
    cmds:
      - terraform init

  pipe_init:
    cmds:
      - task init_artifact
      - task init_webshop

  apply_artifact:
    dir: infra/artifact_repository
    cmds:
      - terraform apply -auto-approve

  setup_image:
    dir: server
    cmds:
      - |
        docker build --platform linux/amd64 -t europe-west1-docker.pkg.dev/dynamicdealmakers-7012254/dd-repo/dd_webshop:v0.0.15 . -f Dockerfile
        docker push europe-west1-docker.pkg.dev/dynamicdealmakers-7012254/dd-repo/dd_webshop:v0.0.15
  apply_webshop:
    dir: infra/webshop
    cmds:
      - terraform apply -auto-approve

  build_infra:
    cmds:
      - task pipe_init
      - task apply_artifact
      - task setup_image
      - task apply_webshop

  destroy_artifact:
    dir: infra/artifact_repository
    cmds:
      - terraform destroy -auto-approve

  destroy_webshop:
    dir: infra/webshop
    cmds:
      - terraform destroy -auto-approve

  destroy_infra:
    cmds:
      - task destroy_webshop
      - task destroy_artifact

  request-cloud-scrape:
    dir: server
    cmds:
      - 'curl --header "Authorization: Bearer $(gcloud auth print-identity-token)" {{.SERVICE_URL}}/scrape-data'

  request-cloud-prices:
    dir: server
    cmds:
      - 'curl --header "Authorization: Bearer $(gcloud auth print-identity-token)" {{.SERVICE_URL}}/prices'
