version: '3'

tasks:
  setup_image:
    cmds:
      - |
        docker build --platform linux/amd64 -t dd_webshop:latest . -f Dockerfile
        docker tag dd_webshop:latest europe-west4-docker.pkg.dev/dynamicdealmakers-7012254/dd-repo/simulator:latest
        docker push europe-west4-docker.pkg.dev/dynamicdealmakers-7012254/dd-repo/dd_webshop:latest

  build_infra:
    cmds:
      - terraform apply -auto-approve
