[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dynamicpricing"
version = "0.1.0"
description = "Pricing model endpoint server"

dependencies = [
  "fast-api"
]

